# Generated by Django 4.2 on 2026-01-12 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_testattempt_completed_testattempt_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Variant', 'verbose_name_plural': 'Variantlar'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Fikr-mulohaza', 'verbose_name_plural': 'Fikr-mulohazalar'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Modul', 'verbose_name_plural': 'Modullar'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AlterModelOptions(
            name='testattempt',
            options={'verbose_name': 'Test urinishi', 'verbose_name_plural': 'Test urinishlari'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name="To'g'ri javobmi?"),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question', verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Variant matni'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='module',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Daqiqalarda kiritng', verbose_name='Davomiyligi (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Modul nomi'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='module',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='quiz.subject', verbose_name='Fan'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Rasm (ixtiyoriy)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1, verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='question',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.module', verbose_name='Modul'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', "Ko'p tanlovli (Test)"), ('CODE', 'Kod yozish (Amaliy)')], default='MCQ', max_length=4, verbose_name='Savol turi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Savol matni'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subjects/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Fan nomi'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Tugatilgan'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='correct_answers',
            field=models.IntegerField(default=0, verbose_name="To'g'ri javoblar"),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='date_taken',
            field=models.DateTimeField(auto_now=True, verbose_name='Topshirilgan sana'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.module', verbose_name='Modul'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='total_questions',
            field=models.IntegerField(default=0, verbose_name='Jami savollar'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
