# Generated by Django 6.0.1 on 2026-01-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_choice_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='text_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Variant matni'),
        ),
        migrations.AddField(
            model_name='choice',
            name='text_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Variant matni'),
        ),
        migrations.AddField(
            model_name='choice',
            name='text_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Variant matni'),
        ),
        migrations.AddField(
            model_name='module',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='module',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='module',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='module',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Modul nomi'),
        ),
        migrations.AddField(
            model_name='module',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Modul nomi'),
        ),
        migrations.AddField(
            model_name='module',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Modul nomi'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Savol matni'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Savol matni'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Savol matni'),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Fan nomi'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Fan nomi'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Fan nomi'),
        ),
        migrations.AlterField(
            model_name='module',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Daqiqalarda kiriting', verbose_name='Davomiyligi (daqiqa)'),
        ),
    ]
